### ISSUE TITLE
Handle Build-Only Dependencies

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#230] opened 2022-08-21 02:55 UTC
From #226's

> Can the tool exclude build-only dependencies? I've noticed that by default is includes them.

Investigate and implement a way to handle the various types of dependencies ([documentation reference](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)). In particular, we should allow customization of:

- Inclusion/exclusion of `[build-dependencies]`
- Inclusion/exclusion of `[dev-dependencies]`
- Inclusion/exclusion of `optional` dependencies
  - Properly setting the [`scope`](https://cyclonedx.org/docs/1.3/xml/#type_scope) on the `Component`

### Acceptance Criteria

- [ ] Customizations are available as CLI arguments
- [ ] Customizations are available as configurations in the cargo metadata

**Comment by xemwebe** [comment] 2023-09-28 07:51
Apparently, the tool always filters on "normal" dependencies, e.g. line 386 in generator.rs:
```
        .filter(|d| d.kind() == DepKind::Normal);
```
The problem is, that `DepKind` is always set to `Normal`, even for build or dev dependencies.

**Comment by lfrancke** [comment] 2023-09-28 09:02
We currently rely on the internal crates API which is unstable and does not - as far as I'm aware - rely on `Cargo.lock` but it parses `Cargo.toml` instead.

That said: This implementation will change.
We're not allowed to talk about it just yet but should be able to announce something second week of October that will help give this project a fresh start.
Please just wait a tiny bit longer.

**Comment by lfrancke** [comment] 2023-10-19 12:56
I can now share what I wasn't allowed to a few weeks ago: https://stackable.tech/en/empowering-rust-projects/

**Comment by lfrancke** [comment] 2023-10-31 23:21
We made a lot of changes in the last weeks so I wanted to give a quick update here.

> Inclusion/exclusion of [build-dependencies]

Build dependencies are included and there's no way to configure this.
The original requestor in #226 also agrees that this makes sense.

> Inclusion/exclusion of [dev-dependencies]

Dev dependencies are excluded and there's no way to configure this

> Inclusion/exclusion of optional dependencies
>        Properly setting the [scope](https://cyclonedx.org/docs/1.3/xml/#type_scope) on the Component

Optional dependencies are excluded but as we now support feature selection they can be included by passing the correct feature flags. In that case they will _not_ be marked as _optional_ in _scope_ which I tend to think is correct as they probably are not optional anymore at this point.

I currently don't see a need to configure this behavior and would close this issue.
Happy to reopen when/if we find use-cases where this is needed.

**Closed** 2023-10-31 23:40 UTC
Labels: enhancement, cargo-cyclonedx
